#cloud-config
# Cloud: Hetzner Cloud (though this may work with your cloud without any changes)
# Instance Type: Shared vCPU, CPX11 (2 vCPU, 2GB RAM)
# OS: Ubuntu 22.04
# This installs Proton Mail Bridge and exposes it on the network with
# an SSL certificate from Let's Encrypt.
#
# Please specify your new Proton Mail Bridge's hostname below, and the email address
# to use with the Let's Encrypt SSL certificate registration.
#
runcmd:
  - sleep 6
  - echo "\n\n\nBeginning installation and configuration of Proton Mail Bridge.\n\n" >/dev/tty1
  - sleep 2
  - apt-get update >/dev/null 2>&1
  - apt-get install -y curl ufw >/dev/null 2>&1
  - ufw allow ssh >/dev/null 2>&1
  - ufw allow http >/dev/null 2>&1
  - ufw allow 993 >/dev/null 2>&1
  - ufw allow 587 >/dev/null 2>&1
  - ufw enable >/dev/null 2>&1
  - apt-get upgrade -y >/dev/null 2>&1
  - echo "#!/bin/bash\n/root/create-protonmail-bridge-system.sh 'proton-bridge.your-domain.com' 'you@your-domain.com'" >/root/create-protonmail-bridge-system-with-args.sh
  - chmod 700 /root/create-protonmail-bridge-system-with-args.sh
  - curl -Ls https://raw.githubusercontent.com/mattx86/protonmail-bridge-cloud-config/main/create-protonmail-bridge-system.sh -o /root/create-protonmail-bridge-system.sh
  - chmod 700 /root/create-protonmail-bridge-system.sh
  - su -P -s /bin/bash -c /root/create-protonmail-bridge-system-with-args.sh - root >/dev/tty1 2>&1
